### ISSUE TITLE
brush spike invalide sub-command

### ISSUE THREAD

**Issue by Darkvodou** [Brennian/Arceon#1]
The brush spike don't work properly in 1.16.5

Fawe version : FastAsyncWorldEdit-Bukkit-1.17-419.jar

Arceon version : Arceon-0.3.1_1.15+.jar

No errors in console

attach files contain screenshot of what FAWE respond me to the command /brush spike

![fawe-brush-spike](https://user-images.githubusercontent.com/46628306/146650931-12f63ffd-d2d8-4757-aeb6-d21d7e03d209.PNG)

**Comment by Feeezin** [comment]
Same problem
Tried to configure with properties, nothing(

**Comment by Darkvodou** [comment]
> Same problem Tried to configure with properties, nothing(

it's /ab spike ( for arceon brush )

**Comment by Feeezin** [comment]
> 

0-0. You create my day, thanks soo much❤
