### ISSUE TITLE
//spike with convex selection broken in 1.20 Arceon

### ISSUE THREAD

**Issue by Tristinack** [Brennian/Arceon#2]
Version 1.20.1

//spike no longer accepts convex selections, only cuboid ones. This means that you can no longer wrap spikes around things or have spikes with curves, only really static diagonal spikes.

This was not a problem in 1.19.4 before I updated my Arceon plugin.

**Comment by inxomnyaa** [comment]
#1 related?

**Comment by Tristinack** [comment]
#1 is unrelated, it's an issue from two years ago with a different command. They were having trouble with /arcbrush spike, which doesn't do the same thing as //spike.

**Comment by Tristinack** [comment]
Resolved, somehow my friend installed it wrong. Works fine for me, he's just silly.
